server:
  port: 8080
  servlet:
    context-path: /demo
spring:
  rabbitmq:
    host: 47.106.122.230
    port: 8152
    username: test
    password: test
    virtual-host:
    # 手动提交消息
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
